name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build Nest.js App
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Package for release
        run: |
          mkdir -p dist/release
          cp -r dist/* dist/release
